### PR TITLE
Fix timezone typo

### PR DESCRIPTION
**Pull request by mayhem**
@massdosage pointed out a minor typo on our timezone selection page. Thanks!

### CODE REVIEW

**Review by massdosage — APPROVED** [review]
Ah, if I'd known where this was I would have raised a PR myself. Next time!

**Comment by massdosage** [comment]
Hmm, a test related to the user timezone page is failing...

**Comment by mayhem** [comment]
Yeah, looking into it now, but my React foo isn't very strong yet. Asked for help.

**Comment by mayhem** [comment]
OK, going back to bed, I learned something new today. Day is finished! :)

**Pull request merged**
