### PR TITLE
Removed SpotifyAPIService class

### PR DESCRIPTION
**Pull request by rimma-kubanova**
# Problem

- There was a class SpotifyAPI service, which is currently is not used since all API requests are processed on backend. 

# Solution

- As @MonkeyDo suggested in IRC, decided to completely remove with class except from one function what is in use. (getAlbumArtFromSpotifyTrackID). This function was moved to frontend/utils/utils.tsx

### CODE REVIEW

**Comment by AviGawande** [comment]
hello @rimma-kubanova could you please help me in in the listenbrainz setup, while setting up the development environment locally i am having the problem of https, if you suggest me some documentations or resources for setting up the listenbrainz locally

**Comment by rimma-kubanova** [comment]
Hi @AviGawande ! Sorry for the late response, with exactly which one you are having problems with? I suggest you setup your listenbrainz server using this documentation https://listenbrainz.readthedocs.io/en/latest/developers/devel-env.html

It's super useful!

**Comment by AviGawande** [comment]
> Hi @AviGawande ! Sorry for the late response, with exactly which one you are having problems with? I suggest you setup your listenbrainz server using this documentation https://listenbrainz.readthedocs.io/en/latest/developers/devel-env.html
> 
> It's super useful!

I am on windows machine is it necessary for having the ubuntu OS for setting up the local development server.

**Comment by rimma-kubanova** [comment]
> > Hi @AviGawande ! Sorry for the late response, with exactly which one you are having problems with? I suggest you setup your listenbrainz server using this documentation https://listenbrainz.readthedocs.io/en/latest/developers/devel-env.html
> > It's super useful!
> 
> I am on windows machine is it necessary for having the ubuntu OS for setting up the local development server.

It might be. Personally, I'm using MacOS, and it works fine

**Comment by AviGawande** [comment]
> > > Hi @AviGawande ! Sorry for the late response, with exactly which one you are having problems with? I suggest you setup your listenbrainz server using this documentation https://listenbrainz.readthedocs.io/en/latest/developers/devel-env.html
> > > It's super useful!
> > 
> > 
> > I am on windows machine is it necessary for having the ubuntu OS for setting up the local development server.
> 
> It might be. Personally, I'm using MacOS, and it works fine

do you know anyone who will help me in sorting this out.. I had couple of hours setting it up in my machine.

**Comment by amCap1712** [comment]
@AviGawande Hi! Please reach out to us in #metabrainz IRC to ask questions about the development setup.

**Comment by AviGawande** [comment]
> @AviGawande Hi! Please reach out to us in #metabrainz IRC to ask questions about the development setup.

i had already asked question about the windows setup on the #IRC channel on Kiwi as well as libra.chat but no one replied, what to do .

**Comment by amCap1712** [comment]
@AviGawande, the developers were probably not active when you asked your questions. You'll have to join the channel and stay around for a few hours.

**Review by MonkeyDo — APPROVED** [review]
Thank you for this cleanup !
Less code, fewer bugs ! :)

**Pull request merged**
