### PR TITLE
LB-1499: Update incremental dumps documentation

### PR DESCRIPTION
**Pull request by rimma-kubanova**
# Problem

[LB-1499](https://tickets.metabrainz.org/browse/LB-1499)
Documentation about incremental dumps is outdated.

# Solution

-updated the doc

### CODE REVIEW

**Review by mayhem — APPROVED** [review]

**Comment by amCap1712** [comment]
Hi! Thanks for the PR but this issue was assigned to someone else and they also submitted a PR for this a day or two ago. And I just got a notification that you have reassigned another ticket (LB-1505) which someone else was working on to yourself without any discussion. Please do not do this again before talking to us in the channel first. 

And for the two tickets here, I will be reviewing the PRs opened by the original assignees of these tickets before this.

**Comment by rimma-kubanova** [comment]
@amCap1712 Hello! Oh, I'm terribly sorry about that, I don't think I havent noticed someone already working on this issue, I'm sorry for my ignorance. And reassigning the task to myself was also not my intention, I'll be more attentive next time. For the future, I'll try not to repeat this and wanted to ask - can I assign any tasks with unassigned status or is it better to ask on IRC in advance?

**Comment by amCap1712** [comment]
@rimma-kubanova Cool, Thanks. Assigning any tasks with unassigned status is fine. If it's already assigned then yes ask in IRC first.

**Review by amCap1712 — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
