### PR TITLE
Update listen additional_info metadata added to spotify listens

### PR DESCRIPTION
**Pull request by alastair**
We updated the documentation for what metadata to put in a listen. This PR updates listens added by our spotify reader to follow this format.

We added the following new fields to the documentation, but I didn't add all of them:

* origin_url - added, same as spotify_id
* music_service - added, 'spotify.com' as per our guides
* submission_client - added, set to 'listenbrainz'

Not added:
* media_player, media_player_version - we don't know what client the user is using to listen, so don't fill this in. It's not always going to be the spotify app
* submission_client_version - does it make sense to have a "version" of the spotify reader?
* music_service_name - we proposed music_service (as a domain), and music_service_name only if you are unable to identify a domain, so I skipped this. We could add it in anyway if we wanted, but I don't think it's needed.

Deprecated fields:
* `'listening_from': 'spotify'` because it's replaced by `'music_service': 'spotify.com'`

### CODE REVIEW

**Comment by alastair** [comment]
Additional question - should we also add submission_client to the last.fm importer? I don't think we have data from this API to fill in any other fields.

**Review by amCap1712 — APPROVED** [review]
LGTM, Thanks!

**Comment by amCap1712** [comment]
Adding the fields to Last.FM importer sounds good.

**Review by MonkeyDo — APPROVED** [review]
:rocket:

**Pull request merged**
