### PR TITLE
Updated FontAwesome dependencies

### PR DESCRIPTION
**Pull request by KasukabeDefenceForce**
# Problem
Added a new art creating. I used certain icons which were not loading because of version mismatch of the font awesome packages. 

# Solution
Updated font awesome dependencies to the latest version.

# Action

### CODE REVIEW

**Review by MonkeyDo — APPROVED** [review]
Good for me ! :rocket:

**Comment by MonkeyDo** [comment]
@KasukabeDefenceForce I had a look at the failing tests.
You're going to have to regenerate and commit the snapshot files (part of our test suite) by running this command: `./test.sh fe -u` (for reference it's a bit hidden in [the docs](https://listenbrainz.readthedocs.io/en/latest/developers/devel-env.html#test-your-changes-with-unit-tests))

**Comment by KasukabeDefenceForce** [comment]
image

@MonkeyDo  I noticed some of the icons are broken so, I am working on correcting it.

**Comment by KasukabeDefenceForce** [comment]
I have fixed the broken icons.

**Review by MonkeyDo — CHANGES_REQUESTED** [review]
I deployed the PR to beta.listenbrainz.org to check it out.

Looks like there is an issue with the standard size of the icons, or something like that. Compare these screenshots between prod and beta: the vertical dots menu icon on the listencards is much thinner which makes it harder to click
PROD:
image
BETA:

**Review by MonkeyDo — APPROVED** [review]

**Pull request merged**
