### PR TITLE
Undo change that added clickable username in navbar

### PR DESCRIPTION
**Pull request by gentlecat**

### CODE REVIEW

**Comment by gentlecat** [comment]
Can someone test this please? Don't have a VM set up.

**Comment by mayhem** [comment]
It didn't seem to work. :(

**Comment by gentlecat** [comment]
Yeah, we need to remove link on that element. :confused:

**Comment by gentlecat** [comment]
Please check.

**Comment by mayhem** [comment]
Seems to be undone correctly. :rabbit2:

**Comment by gentlecat** [comment]
:sheep:ing

**Pull request merged**
