### PR TITLE
LB-988: Separate CSS/LESS definitions pertaining to BrainzPlayer

### PR DESCRIPTION
**Pull request by tandy-1000**
https://tickets.metabrainz.org/browse/LB-988

Moved LESS styles for BrainzPlayer into a new file in preparation for making BP a library.

### CODE REVIEW

**Comment by tandy-1000** [comment]
Any chance of review @MonkeyDo ?

**Comment by MonkeyDo** [comment]
Sure thing @tandy-1000 , I'll get to it probably tomorrow.
In the meantime, it looks like the snapshots need to be regenerated again: https://github.com/metabrainz/listenbrainz-server/runs/4172367495?check_suite_focus=true#step:8:1912

**Comment by tandy-1000** [comment]
Hmm, I tried to run that command, but I get a bunch of jsdom errors, probably to do with my devenv not being setup properly, I'll try do it properly soon.

**Comment by tandy-1000** [comment]
> Want me to generate the snapshots for now? I've got the PR open currently to review it, so it's really no bother

Yes please! thanks:)

**Review by MonkeyDo — APPROVED** [review]
Looks great, thanks a lot for your help !
One small step closer ;)

I'll wait for tests to pass before merging.

**Pull request merged**
