### PR TITLE
STFU heisentest!

### PR DESCRIPTION
**Pull request by mayhem**
Trying heisentest mitigation strategies.

### CODE REVIEW

**Comment by mayhem** [comment]
@brainzbot please retest this again, yo!

**Comment by mayhem** [comment]
@brainzbot, sorry to be bothering you so much, but would you be so kind as to retest this again?

**Comment by mayhem** [comment]
@brainzbot retest this you lazy sod!

**Comment by mayhem** [comment]
@brainzbot please retest, pretty please?

**Comment by mayhem** [comment]
@brainzbot retest this please

**Comment by mayhem** [comment]
I don't think this mitgation has ever been triggered, but it doesn't seem to cause problems. should we merge it and see?

**Review by paramsingh — APPROVED** [review]
Seems pretty safe, considering we never run this in production anyways.

**Pull request merged**
