### PR TITLE
Show track and artist name in "Link with MusicBrainz" modal

### PR DESCRIPTION
**Pull request by vibhoooo**
Hi there!
I modified the render function and implemented what you said.Now artist name and track name are showing correctly in the dialog box.
I am attaching a ss.
[EDIT]: updated snapshot
Screenshot 2023-01-17 at 2 17 42 AM

### CODE REVIEW

**Comment by MonkeyDo** [comment]
I think design-wise, you should aim to be closer to how we display tracks in the rest of the website:
image

You could even try to use the ListenCard component (how we display tracks on the website) like so:
https://github.com/metabrainz/listenbrainz-server/blob/0705db9fd7ee696841db55323d4c3df49c47d51f/frontend/js/src/year-in-music/2021/ComponentToImage.tsx#L116-L134

**Comment by vibhoooo** [comment]
Okay thanks for review.I will try to make the required changes.

**Comment by vibhoooo** [comment]
@MonkeyDo 
Hi there!
Now it is looking like this ->
Screenshot 2023-01-14 at 3 02 29 AM

**Comment by vibhoooo** [comment]
@MonkeyDo 
May you please help me debug why tests are failing?

**Comment by MonkeyDo** [comment]
> @MonkeyDo May you please help me debug why tests are failing?

We have a failsafe type of test to catch changes to our UI called [snapshots](https://jestjs.io/docs/snapshot-testing).
Here the failing test is a failing snapshot: https://github.com/metabrainz/listenbrainz-server/actions/runs/3917276608/jobs/6696973331#step:6:10223

This is expected, as the UI has changed !

To update the snapshot, you'll need to run the command `./test.sh fe -u`.
It's documented —but not very prominently— in [the developer docs](https://listenbrainz.readthedocs.io/en/latest/developers/devel-env.html?highlight=snapshots#test-your-changes-with-unit-tests), for future reference.
Once you've run that, you'll need to commit and push the updated snapshot file.




As for the screenshot you posted, I think  it's getting a lot better !
The track title is *very big* though and sticks out too much.
You'll want to revise the css styles. And while I'm at it, I'd rather see those styles defined in our LESS/CSS files rather than in a style property in the react component :)

**Comment by vibhoooo** [comment]
@MonkeyDo 
I have made the required changes
Now it's look like this ->
Screenshot 2023-01-17 at 2 17 42 AM

**Comment by vibhoooo** [comment]
Is the file that I have committed for snapshot incorrect?

**Comment by MonkeyDo** [comment]
> Is the file that I have committed for snapshot incorrect?

I do believe so, yes. try running the `./test.sh fe -u` command again and seeing if any snapshots need to be committed.

**Comment by MonkeyDo** [comment]
I took the liberty of updating the PR and the recreating the snapshot files, I hope you don't mind, I wanted to push this along since it's basically finished :)

**Pull request merged**
