### PR TITLE
LB-225: Add support for importing data dumps.

### PR DESCRIPTION
**Pull request by paramsingh**
Based off #272, so will need to be rebased after that.

There are a bunch of things more to do here, for example the stats table has a foreign key to the user table so the stats tables can't be imported alone, it needs a corresponding entry in the user table. Not sure how to solve this, other than sanitizing users and putting it in the stats dump too.

### CODE REVIEW

**Comment by paramsingh** [comment]
Added tests too.

**Comment by mayhem** [comment]
Rebase, please

**Comment by paramsingh** [comment]
I would love opinions on the problem I mentioned in the OP. The stats dump currently cannot be imported alone, it needs a corresponding private dump.

>the stats table has a foreign key to the user table so the stats tables can't be imported alone, it needs a corresponding entry in the user table. Not sure how to solve this, other than sanitizing users and putting it in the stats dump too.

**Comment by mayhem** [comment]
Oh sorry, didn't see that question:

> Not sure how to solve this, other than sanitizing users and putting it in the stats dump too.

That is exactly how MB does it -- lets do that too.

**Comment by paramsingh** [comment]
[LB-240](https://tickets.metabrainz.org/browse/LB-240) and #293

**Comment by paramsingh** [comment]
Rebased over #293 and added logic to only import user table from stats dump when needed.

**Pull request merged**
