### PR TITLE
LB Production Switch Changes

### PR DESCRIPTION
**Pull request by paramsingh**
Change header from pre-beta to beta, remove banner warning and update config.BETA_URL.

### CODE REVIEW

**Comment by mayhem** [comment]
For ease of migration can you also please make the config changes to consul_config.py.ctmpl ? You should be able to make our what needs to happen.

**Comment by paramsingh** [comment]
Okay, working on it.

**Comment by paramsingh** [comment]
Seems like they are variable in `consul_config.py.ctmpl` and retrieved from [docker-server-configs](https://github.com/metabrainz/listenbrainz-server/blame/master/consul_config.py.ctmpl#L2)? https://github.com/metabrainz/listenbrainz-server/blob/master/consul_config.py.ctmpl#L70

**Comment by mayhem** [comment]
Please ignore my last comment, I'm still not remembering the flow of secret data through our system correctly.

**Comment by paramsingh** [comment]
Okay, on it.

**Comment by paramsingh** [comment]
Added parameters for vhost, username and password in rabbitmq.

There is some code duplication that could be fixed with some refactoring, but I'm hoping we can move forward with it for now. I've created a ticket for fixing it: [LB-196](https://tickets.metabrainz.org/browse/LB-196).

**Pull request merged**
