### PR TITLE
Fixes lb-46

### PR DESCRIPTION
**Pull request by mayhem**
Don't leak filehandles.

### CODE REVIEW

**Comment by gentlecat** [comment]
[`finally`](https://docs.python.org/2/tutorial/errors.html#defining-clean-up-actions)?

**Comment by mayhem** [comment]
Does finally get called even when an exception is raised?

**Comment by gentlecat** [comment]
> A finally clause is always executed before leaving the try statement, whether an exception has occurred or not.

**Comment by mayhem** [comment]
\ø/

**Comment by alastair** [comment]
:car:

**Pull request merged**
