### PR TITLE
Add OpenAPI spec

### PR DESCRIPTION
**Pull request by vibhoooo**
Modified the previous PR and added OpenAPI spec.

### CODE REVIEW

**Comment by vibhoooo** [comment]
@amCap1712 
May you please help debug where checks are failing.

**Comment by amCap1712** [comment]
@vibhoooo Hi! Sorry for the delay. I am currently busy with other stuff but will try to take a look at this soon.

**Comment by vibhoooo** [comment]
Okay no problem.I am trying to resolve it till then.

**Comment by vibhoooo** [comment]
@amCap1712
I made some changes in `appmap-python` after communicating with the appmap comnmunity in their slack channel and after that I removed the tmp and appmap.yml files and kept the OpenAPI spec.
OpenAPI spec is successfully generated and all the checks are passing.
Thanks

**Comment by amCap1712** [comment]
Hi @vibhoooo! I took a look at this. The schema has lot of issues and is missing many details. I also took a look at how BookBrainz implements Swagger UI, https://github.com/metabrainz/bookbrainz-site/blob/master/src/api/routes/author.js#L41-L103. The docs are written in a way that a swagger/open api library can parse. I think we should take the same approach for LB. Feel free to reach out to me in the IRC channel for further discussion.

**Comment by vibhoooo** [comment]
Hi there!
Okay I will try to work on it and will update you on IRC channel.
Thanks for the review.

**Pull request closed without merging**
