### PR TITLE
LB-783: Add URL to ListenBrainz dumps

### PR DESCRIPTION
**Pull request by alastair**
# Problem
There was no place in the documentation that linked to the URL where LB dumps are available

# Solution

Add a link

Screenshot 2021-05-10 at 10 49 33 AM

### CODE REVIEW

**Comment by amCap1712** [comment]
While we are at it, let's add data.mb.org to https://github.com/metabrainz/listenbrainz-server/blob/master/listenbrainz/webserver/templates/index/data.html as well.

**Comment by alastair** [comment]
hah, I didn't even know that there was a page on listenbrainz.org! Maybe we shouldn't have it in 2 different places. Thoughts?

**Comment by amCap1712** [comment]
Neither did I till a few minutes ago. I think it makes sense to have it in one place only so as to avoid confusion. Let's just data.mb to the webpage then? If we want, we can link to the webpage from the documentation instead of directly adding the links there.

**Comment by alastair** [comment]
Updated to make the data page more detailed, and docs just links to the data page:

Screenshot 2021-05-10 at 1 05 12 PM

Screenshot 2021-05-10 at 1 05 24 PM

**Review by amCap1712 — APPROVED** [review]
Looks good! Thanks.

**Pull request merged**
