### PR TITLE
LB-92: Fix existing test setup

### PR DESCRIPTION
**Pull request by gentlecat**
http://tickets.musicbrainz.org/browse/LB-92

### CODE REVIEW

**Comment by mayhem** [comment]
All checks failed!

(/me runs away really fast)

**Comment by mayhem** [comment]
Was that all there is to it? If so, LGTM.

**Comment by mayhem** [comment]
is there a particular bit that you're looking for feedback on? If not, I don't see the point of doing WIP PRs. This is just noise in my very busy inbox...

**Comment by gentlecat** [comment]
I didn't even assign you to this, so not sure why you are getting notifications. I need to have a pull request  to be able to automatically test my updates.

**Comment by mayhem** [comment]
The BDFL has magical powers, didn't you know?

(more seriously, instead of "No description provided." give us a reason why you are opening a PR.)

**Comment by gentlecat** [comment]
> I need to have a pull request to be able to automatically test my updates.

"Fix existing test setup" seems to be descriptive enough.

**Comment by mayhem** [comment]
> "Fix existing test setup" seems to be descriptive enough.

I disagree, which is why I am having this conversation with you.. This would be much clearer:

Title: "Test PR to ensure that our test/jenkis setup is working."
Desc: "This is a test PR. Please ignore this since it being used for testing."

**Comment by gentlecat** [comment]
It's not a *test* PR. It's a PR that fixes tests. I welcome any constructive feedback on the changes I'm making, but there's more to it then just code. I also need to configure Jenkins correctly. *[WIP]* means that I'm still working on it and it's not ready to be merged. When it is ready, I'll assign someone to take a look at it if it hasn't happened after my last update.

I'm sorry that this is a noise in your inbox. Pretty sure you can reconfigure notifications on GitHub to notify you only when you are mentioned/assigned to things on repos that you are watching.

I don't have a lot of mental energy to work on multiple things at once these days. So please let me fix this and move on, that's what you asked me to do. Your sarcastic comments aren't helping.

**Comment by mayhem** [comment]
>  So please let me fix this and move on, that's what you asked me to do.

This is precisely how I feel when you comment on whitespace issues in my PRs. Can we agree to just chill out a little?

**Comment by gentlecat** [comment]
Well, code style is something I care about, so I point out issues when I see them. Unfortunately there's no good automatic formatting tool for Python that I know of, apart from some integrated in IDEs. If you don't care about these issues, that's fine, just ignore my comments.

**Comment by mayhem** [comment]
This is where we disagree. Whitespace, unless it impacts the functioning of the program, is NOT an issue. Please don't point it out. If you feel that it is so important, please fix it yourself.

**Pull request merged**
