### PR TITLE
LB-1309: Implement stats art generator

### PR DESCRIPTION
**Pull request by KasukabeDefenceForce**
# Problem

# Solution

# Action

### CODE REVIEW

**Comment by KasukabeDefenceForce** [comment]
Page mock up: -
https://www.figma.com/file/YRbCOtFHBez8XmMdCKbGta/ListenBrainz-redesign?type=design&node-id=0-1&mode=design&t=Se4mPr1985j13N10-0

**Comment by KasukabeDefenceForce** [comment]
@MonkeyDo  I need help on these issues:
1.Positioning the settings sidebar so that there is no gap between it and the header. Removing the margin of the secondary navbar might solve it.
2. How to display the toggle buttons correctly. I am unable to adjust the margin between the text and switch.
3. Working of the various toggle buttons.
4. How can I copy the functionality of magic share button to my custom styled button.

**Comment by MonkeyDo** [comment]
> @MonkeyDo I need help on these issues: 1.Positioning the settings sidebar so that there is no gap between it and the header. Removing the margin of the secondary navbar might solve it. 2. How to display the toggle buttons correctly. I am unable to adjust the margin between the text and switch. 3. Working of the various toggle buttons. 4. How can I copy the functionality of magic share button to my custom styled button.

:+1: OK, leave it with me I will work on the CSS styling as I see a fair amount that can be refactored and I know this website's CSS like the back of my hand ;)
Will also look into the share button.

There will be a lot of functionality from those settings that will be missing for this first implementation (we don't have the features in the back-end yet), so I will make sure they can look good for the future but will comment them out for the time being.

**Comment by MonkeyDo** [comment]
I think this is ready for beta version. I'll merge the PR and deploy it, then we can get some feedback from our users and go from there.

**Pull request merged**
