### PR TITLE
LB-837: Filter out playlist owner from collaborators

### PR DESCRIPTION
**Pull request by MonkeyDo**
We already do this on the back-end, but confusingly allow it on the front-end, leading to LB-837, which is a minor issue but still…
Added a test for it too.
Also fixed a React warning: "Each child in a list should have a unique "key" prop."

### CODE REVIEW

**Review by amCap1712 — COMMENTED** [review]
Change LGTM. But how about instead show an error that you cannot add yourself as a collaborator and not adding the name to list when Add collaborator is clicked. Thoughts?

**Comment by MonkeyDo** [comment]
OK, I opted for disabling the button when a logged in user writes the name of the playlist owner (or their own name for a playlist being created)

**Comment by MonkeyDo** [comment]
Also updated the Playlist*s* page (I only did the Playlist page previously) with the previous filtering of playlist owner.

**Review by amCap1712 — APPROVED** [review]
LGTM. Thanks

**Pull request merged**
