### PR TITLE
Rework the URL structure:

### PR DESCRIPTION
**Pull request by mayhem**
login: /login
profile: /user/rob
import: /user/rob/import
scraper: /user/rob/scraper.js
get listens: /1/user/rob/listens
submit listens: /1/submit-listens

And add a fetch user by auth token method to the db.user object.

### CODE REVIEW

**Comment by mayhem** [comment]
We just had a length discussion on URL structure in IRC. We agreed to keep the version short.

**Comment by gentlecat** [comment]
It's not about the version that you use in the URL. It's about name of the blueprint that you use in `url_for` calls. `1` is just confusing when I'm looking at `url_for("1.submit_listen", user_id=user_id, _external=True)`.

**Comment by gentlecat** [comment]
And http://chatlogs.metabrainz.org/brainzbot/metabrainz/2015-09-16/?msg=3352140&page=5.

**Comment by alastair** [comment]
This looks good to me. Note thata @gentlecat and I moved import to `/import`, because we can just use the current logged in user to get user details (which makes more sense, because you can only import your data).

**Comment by alastair** [comment]
reminder to me to also deploy api.lb in nginx

**Pull request merged**
