### PR TITLE
Spotify permissions: use array of strings instead of one long string

### PR DESCRIPTION
**Pull request by MonkeyDo**
# Problem

SpotifyPermission type allows one of a fixed number of strings.
 However, the permission string passed down to the react components is one concatenated string with the various permissions

# Solution
Instead, pass an array of permissions down to react components.

### CODE REVIEW

**Comment by MonkeyDo** [comment]
Ugh, i'll have to clean this up thoroughly before it's usable.

**Comment by MonkeyDo** [comment]
@paramsingh I'm going to let you do the python changes. I started locally, but I don't know python well enough to be sure I won't be breaking stuff :p
The front-end stuff is ready to receive an array of permissions.

**Comment by paramsingh** [comment]
Sure, sounds good to me!

**Comment by MonkeyDo** [comment]
@paramsingh Do we still want to do this or should I close it?

**Comment by amCap1712** [comment]
As a part of the youtube player re-implementation, I am working on modifying the spotify_auth table. Is it fine if I take over the python part of this PR?

**Comment by MonkeyDo** [comment]
Yes please @amCap1712 !

**Comment by MonkeyDo** [comment]
Closed in favor of #1404

**Pull request closed without merging**
