### PR TITLE
Show listen count on Artist Origin map (Frontend)

### PR DESCRIPTION
**Pull request by ishaanshah**
# Description
This PR adds Frontend support for coloring the Artist Origin map by listen counts.

# Preview
Peek 2020-12-04 16-38

### CODE REVIEW

**Review by MonkeyDo — COMMENTED** [review]
Looks great, well done!

I would only suggest another name for `countOf`, which I don't find very descriptive or self-explanatory.
What do you think of `metric` or something like `selectedMetric`?

**Comment by ishaanshah** [comment]
Thanks @MonkeyDo for the review, your comment makes sense to me and I have made the necessary changes. Please have a look :).

**Review by MonkeyDo — APPROVED** [review]
Looks good ! 🚀

**Comment by MonkeyDo** [comment]
The failing CI test is unrelated to this PR and a known issue in our CI setup.

**Comment by alastair** [comment]
@brainzbot add to whitelist

**Pull request merged**
