### PR TITLE
Restream data to BigQuery.

### PR DESCRIPTION
**Pull request by paramsingh**
# Summary

* This is a…
    * [ ] Bug fix
    * [x] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

* JIRA ticket (_optional_): 

We missed some data and needed schema changes in BQ, so this script restreams data into
Google BigQuery. It then streams each user's listens into the appropriate table.

# Solution

This script creates new tables for each year, putting all data before 2002 (the year that 
last.fm started) into a `before_2002` table.

# Action

We'll probably need to first get bigquery_writer to work with the new schema before running this.
We should discuss this a bit more.

### CODE REVIEW

**Comment by paramsingh** [comment]
I didn't bother adding tests because this will only be a one-off script. There are some ideas in this such as creating the BQ schema that I think would have a place in manage.py though.

**Comment by mayhem** [comment]
We'll also need to get the reports to work with the new format before we merge/run this.

**Comment by paramsingh** [comment]
A problem that may lead to duplication:

1. We start the restreamer which streams listens according to batches of time (first all listens before 2002, then all listens before 2003 and so on)
2. The streamer sends some listens and dies for some reason (internal error, bigquery bad, anything)
3. We now have no idea about which listens have been sent and which haven't.
4. If we decide to start from the batch we were doing, we risk duplicates.

Possible way to avoid this: We could try resetting the bq dataset and starting over if the restreamer dies.

**Comment by paramsingh** [comment]
Closing for now.

**Pull request closed without merging**
