### PR TITLE
LB-1538: Added ability to add area from settings page

### PR DESCRIPTION
**Pull request by lzzy12**
# Problem

Work on this ticket: https://tickets.metabrainz.org/browse/LB-1538

# Solution

image

### CODE REVIEW

**Comment by Aerozol** [comment]
Thank you!

As a lot of privacy discussion has been happening lately, I'm thinking it would be better to put this part in bold:
**This information will be public.**

**Comment by lzzy12** [comment]
@Aerozol done with the requested change

**Review by amCap1712 — COMMENTED** [review]
Hi!

Thanks for the PR. We first need to discuss how we intend to use areas in LB more extensively so I'll circle back to this PR later.

**Comment by Aerozol** [comment]
Hey @amCap1712, did you want to meet re. this after the next meeting?

**Comment by amCap1712** [comment]
@Aerozol sure, sounds good.

**Comment by Aerozol** [comment]
Hi @Izzy12, this has been added to the next meeting topics, you are welcome to join: https://wiki.musicbrainz.org/MetaBrainz_Meeting

**Comment by Aerozol** [comment]
Thank you @lzzy12, this has been blocked by [LB-1549](https://tickets.metabrainz.org/browse/LB-1549) for now.

**Comment by mayhem** [comment]
One more comment on this -- we're keen to implement this, but we're quite overloaded with a lot of tasks right now and can't afford to open yet another new task right now. Give us 2-3 months and we'll be able to look at it.

**Comment by Techman** [comment]
> Thank you!
> 
> As a lot of privacy discussion has been happening lately, I'm thinking it would be better to put this part in bold: **This information will be public.**

[Since this issue is now closed, please let me know if I should comment this somewhere else.]

At the risk of sounding like a broken record when it comes to privacy concerns, I will ask this: is there a real need for this data to be public?

This is substantially more serious as a user setting a location close to their own (or their own) opens up a lot of doors for...a lot of bad things to happen. With this feature being used for concerts, setting a location that is accurate to the user's actual location is quite high.

I feel that this data should be kept private to ListenBrainz/MetaBrainz and not be publicly viable unless the user wants it to be. Far more strongly than listening data itself.

**Comment by mayhem** [comment]
There are two phases to this project: 1. Deal with an internal migration of our OAuth accounts from MusicBrainz to MetaBrainz. During this move the area setting that a user has given us will move to the MetaBrainz profiles. And this data, since it is already public, will continue to be public. 2. Work out how to make concert listings in LB work. We haven't worked out the details on and and I don't really care to do this right now, since we're not working on this yet. That said there are a lot of moving parts and open questions -- and if the concert areas for a user are going to public or private hasn't been addressed yet.

Lets please just leave this be for now. We'd like to focus on doing the things that are blocking the fun things like this feature.

**Pull request closed without merging**
