### PR TITLE
merge production into master.

### PR DESCRIPTION
**Pull request by paramsingh**
This should remove the confusion due to `BETA_URL`

### CODE REVIEW

**Comment by paramsingh** [comment]
I'm not sure if this is okay to merge, this would cause the variable to be BETA_URL in production and API_URL in master, which will need to be fixed then? Maybe first a PR to change to API_URL in production and then a merge of production into master might be better?

**Comment by mayhem** [comment]
Yes, I am not anywhere near ready to merge this. I'll handle with care when the time comes.

**Comment by mayhem** [comment]
I think this PR is now ready for merging -- should we possible redo or rebase this?

**Comment by paramsingh** [comment]
On it.

**Pull request merged**
