### PR TITLE
[Fix: LB-89] BadRequest error when importing while now_playing

### PR DESCRIPTION
**Pull request by pinkeshbadjatiya**
Fixes [LB-89](http://tickets.musicbrainz.org/browse/LB-89)
The audioscrobbler API's output differs when requesting listens using getrecenttracks method in case when the user is playing song. In case of `now_playing` to be true, the API outputs 1st listen as the now_playing.  
When listening: `{"@attr": {"now_playing":"true"}}`
When not listening: `{"date": {"utc":"12345756", "#text":"21 Jul 2016, 10:22"}}`

### CODE REVIEW

**Comment by alastair** [comment]
This looks good. Can you add a comment which explains why we do this (in case we come back to the code in future weeks or months and forget what it does)

**Comment by pinkeshbadjatiya** [comment]
Updated the description for the same.

**Comment by alastair** [comment]
I meant a comment in the code. Please make sure you use similar words to what are in the code. For example, your code says:

    if ('listened_at' in result) {

and nowhere in the description you added you use the word `listened_at`, only `now_playing`

**Comment by pinkeshbadjatiya** [comment]
Updated the description in code.

**Pull request merged**
