### PR TITLE
Move set_rate_limits.py

### PR DESCRIPTION
**Pull request by mayhem**
# Description
set rate limiits is in the wrong dir for it to run...

* This is a…
    * ( ) Bug fix
    * (x) Feature addition
    * ( ) Refactoring
    * (x) Minor / simple change (like a typo)
    * ( ) Other

* **Describe this change in 1-2 sentences**:

# Problem

* JIRA ticket (_optional_): 

# Solution

# Action

### CODE REVIEW

**Comment by mayhem** [comment]
Note -- this just moves a file -- it changes nothing else.

**Comment by paramsingh** [comment]
Where was this file earlier?

**Comment by mayhem** [comment]
in listenbrainz-server/listenbrainz , so it could not import python modules.

**Comment by paramsingh** [comment]
Should we remove the old file?

**Comment by paramsingh** [comment]
Although, technically it should work from the dir it was in anyways. Not sure why it doesn't.

**Comment by mayhem** [comment]
Something about this PR turned out wrong. I'm going to toss it and just make the change against master.

**Pull request closed without merging**
