### PR TITLE
Alphabetise AddData.tsx

### PR DESCRIPTION
**Pull request by Aerozol**
Alphabetise lists
Some consistency changes (no fullstops in lists)
Change intro paragraphs to 'active voice'

### CODE REVIEW

**Comment by mayhem** [comment]
Tests failed with:  Error: frontend/js/src/about/add-data/AddData.tsx(26,12): error TS17008: JSX element 'a' has no corresponding closing tag.

**Comment by Aerozol** [comment]
Thanks Rob! I was going to check the tests myself, this time, I swear ;)

Also - make sure you actually want these alphabetised? It seemed logical to me, now that the list is getting long.

**Comment by mayhem** [comment]
Alphabetized is a good plan here -- that doesn't play favorites.

**Review by MonkeyDo — APPROVED** [review]
Yes please !
Ran an incantation to automatically format the page, hope you don't mind.

**Pull request merged**
