### PR TITLE
[WIP] Add basic support for a vagrant VM

### PR DESCRIPTION
**Pull request by mayhem**
First cut at supporting vagrant for listenbrainz. A simple "vagrant up" should do the trick.

### CODE REVIEW

**Comment by gentlecat** [comment]
Not sure I understand, but why do we need a Vagrant VM when there's Docker?

**Comment by mayhem** [comment]
I think there are a few reasons to have a VM: I didn't have much luck with docker on mac and as far as I know there is no docker for windows. Also, installing docker and running docker images is a shitty end user experience -- VB has a bit nicer end user experience than docker does now.

**Comment by gentlecat** [comment]
There are both Mac and Windows versions: https://docs.docker.com/engine/installation/#/on-osx-and-windows.

I'm just trying to understand who's going to use this.

**Comment by mayhem** [comment]
People who don't want to touch docker. Not everyone is geeky like us. Also, I personally despise doing dev work on my mac -- there are always weird problems. A clean VM that I can blow away whenever I want, is a very good working model for me.

I guess I am your target audience. :)

**Comment by gentlecat** [comment]
Alright, sounds reasonable. What's left to be done there?

**Comment by mayhem** [comment]
The postgres permissions thing -- let me see if I can sort that today and then yank this out of WIP.

**Pull request closed without merging**
