### PR TITLE
Convert user profile page to Python/Jinja2

### PR DESCRIPTION
**Pull request by gentlecat**

### CODE REVIEW

**Comment by gentlecat** [comment]
http://tickets.musicbrainz.org/browse/LB-29 should be closed after this is done.

**Comment by gentlecat** [comment]
This is working on all pages except the first one. I get this exception there:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/listenbrainz/webserver/views/user.py", line 48, in profile
    previous_listens = list(cassandra.fetch_listens(user_id, limit=25, from_id=listens[0]["listened_at"] + 1, order="asc"))
  File "/usr/local/lib/python2.7/dist-packages/listenbrainz_store-0.1.0-py2.7.egg/listenstore/listenstore.py", line 184, in fetch_listens
    current_limit, order):
  File "/usr/local/lib/python2.7/dist-packages/listenbrainz_store-0.1.0-py2.7.egg/listenstore/listenstore.py", line 228, in fetch_listens_for_range
    results = self.execute(query, params)
  File "/usr/local/lib/python2.7/dist-packages/listenbrainz_store-0.1.0-py2.7.egg/listenstore/listenstore.py", line 114, in execute
    return self.session.execute(query.encode(), params)
  File "/usr/local/lib/python2.7/dist-packages/cassandra/cluster.py", line 1295, in execute
    result = future.result(timeout)
  File "/usr/local/lib/python2.7/dist-packages/cassandra/cluster.py", line 2799, in result
    raise self._final_exception
InvalidRequest: code=2200 [Invalid query] message="unable to make int from '2148595199'"
```

I guess something is wrong with the API for getting data from Cassandra.

**Comment by mayhem** [comment]
Very interesting that this problem appears now. But the timestamp shown in the error above is an invalid timestamp and overflows a 32 bit int:

Sun, 31 Jan 2038 23:59:59 GMT

I think there is something amiss about the upper range of listen fetches -- I suppose once it gets to the current time, it ought to stop.

**Comment by alastair** [comment]
There already is some stuff in the listenstore about this I think - https://github.com/metabrainz/listenbrainz-server/blob/master/listenstore/listenstore/listenstore.py#L128-L129

**Comment by gentlecat** [comment]
OK, this should work now. :cat2:
cc: @alastair, @mayhem

**Pull request merged**
