### PR TITLE
LB-1508 Allow hiding personal recommendations

### PR DESCRIPTION
**Pull request by Sumit1797**
# Problem

A user can hide recommendations received from another user but not personal recommendations.
(https://tickets.metabrainz.org/browse/LB-1508?filter=12410)

# Solution
Add the ability to hide personal recommendations

# Action
Change the backend api user_timeline_event_api to add an entry for personal recommendations in the hide_timeline_events table in database.

### CODE REVIEW

**Review by amCap1712 — COMMENTED** [review]
Hi! Sorry for the delay. I just came across this PR. Can you please add tests for the feature as well?

**Comment by spoojaryheat** [comment]
> Ping @Sumit1797 Hi! Just wanted to know if you're able to finish the PR, or if one of us should take it over. Thanks for letting us know !

Hi I missed the requested changes. I will update the PR.

**Comment by Sumit1797** [comment]
> Ping @Sumit1797 Hi! Just wanted to know if you're able to finish the PR, or if one of us should take it over. Thanks for letting us know !

Hi I missed the requested changes, I will updated the PR.

**Comment by MonkeyDo** [comment]
@amCap1712 Note that I had to add a small change to the DB SQL scripts which will be required to run when deploying

**Comment by MonkeyDo** [comment]
@Sumit1797 Hope you don't mind, it seemed like life did its thing so I took over since there wasn't much left to do and I wanted to see this PR merged :)

**Comment by Sumit1797** [comment]
> @Sumit1797 Hope you don't mind, it seemed like life did its thing so I took over since there wasn't much left to do and I wanted to see this PR merged :)

No problem, Sorry I couldn't spend more time on it, looking at your code it's a learning for me!

**Comment by MonkeyDo** [comment]
Finished and tested on test.listenbrainz.org, users can hide an event from front-end, then reloading the page shows the hidden event, then users can unhide the event and similarly after a refresh the event is unhidden.

**Pull request merged**
