### PR TITLE
Change time.time to time.monotonic

### PR DESCRIPTION
**Pull request by AbhinavOhri**
# Problem
LB-677

# Solution
When calculating time taken for something use time.monotonic instead of
time.time to avoid errors due to system clock time shifting.

# Action
code review

### CODE REVIEW

**Comment by alastair** [comment]
This looks good, thanks for the contribution!
I see a number of other instances where time was imported as `from time import time`, and therefore it's just called as `time()`.
For example, see listenbrainz_spark/ftp/download.py, listenbrainz_spark/recommendations/create_dataframes.py, listenbrainz_spark/recommendations/train_models.py, and others.

**Comment by shivam-kapila** [comment]
Hi. I think there might be some other occurrences too. You can refer [here](http://livegrep.metabrainz.org/search/livegrep?q=time.time&fold_case=auto&regex=false&context=true&repo%5B%5D=metabrainz%2Flistenbrainz-server)

**Comment by AbhinavOhri** [comment]
@shivam-kapila The link u have posted doesn't  contain the changes from this PR.Also at some places  I have not replaced time.time() intentionally as it is being used for calculating the epoch timestamp for which time.monotonic() doesn't provide the correct value. Therefore , I have only changed time.time() to time.monotonic() where it is used to calculate time taken to do something or difference of time .

**Comment by paramsingh** [comment]
Hey @AbhinavOhri, could you rebase your changes over master once?

**Pull request merged**
