### PR TITLE
Add OpenAPI spec

### PR DESCRIPTION
**Pull request by vibhoooo**
Ticket ->
LB-568
https://tickets.metabrainz.org/browse/LB-568.

Task- >
I have to create an OpenAPI spec for the flask endpoints which can be imported.

Solution -> 
I have used APPMAP for the generation of the OpenAPI spec for the flask endpoints.APPMAP was added to the project.Tests were recorded and finally from each recorded test from http calls APPMAPs were generated and after that OpenAPI spec was generated.

Thank You.

### CODE REVIEW

**Comment by vibhoooo** [comment]
I think all checks have failed.I have to look into this again.

**Comment by amCap1712** [comment]
@vibhoooo This will not fix the checks but you need to update your master branch with metabrainz master branch. If you need help on how to do this, feel free to ask me in IRC (response time may be slow because I am still out of station).

**Comment by amCap1712** [comment]
One other reason checks are failing is because `appmap` is missing from the `requirements.txt` file.

**Comment by vibhoooo** [comment]
@amCap1712 
I will try to update the my master branch.If I get stuck I will ask.
I will try to update the `requirements.txt` file.
Thanks for review.

**Comment by vibhoooo** [comment]
On updating `requirements.txt` tests are still failing.I think there is some other issue.

**Pull request closed without merging**
