### PR TITLE
Removing unnecessary AB icons

### PR DESCRIPTION
**Pull request by dpmittal**
There were unnecessary AcousticBrainz icons in the repo which needed to be removed

### CODE REVIEW

**Comment by alastair** [comment]
Let's make the listenbrainz icons consistent with the ones in MessyBrainz too (https://github.com/metabrainz/messybrainz-server/pull/16/files)

**Comment by dpmittal** [comment]
@alastair I have made the changes :)

**Comment by mineo** [comment]
`favicon-256.png` looks extremely blurry compared to the previous version.

**Comment by dpmittal** [comment]
@mineo Actually it was resized from the existing 32px file which was blurry so all the files became blurry. Now I have resized the files from [this](https://github.com/metabrainz/metabrainz-logos/blob/master/final-logos/ListenBrainz/VECTOR/SVG/ListenBrainz_logo_icon.svg) so now all the files are not blurry

**Comment by dpmittal** [comment]
An now all the icons are squared which were not earlier :)

**Pull request merged**
