### PR TITLE
Fix styling in icon-only mode

### PR DESCRIPTION
**Pull request by shivam-kapila**
# Problem
The follow button appears HUGE and ugly. The hover animation also vanishes. 

image

# Solution

The `btn btn-sm` classes were removed from the follow button component. Adding them fixes the styling and animation.
image

### CODE REVIEW

**Comment by shivam-kapila** [comment]
@MonkeyDo please look into this once the JS builds are triggered (I need to be whitelisted for them :p)

**Comment by MonkeyDo** [comment]
@brainzbot add to whitelist

**Comment by alastair** [comment]
@brainzbot add to whitelist

**Review by MonkeyDo — APPROVED** [review]
CI tests are currently failing for an unrelated issue (https://tickets.metabrainz.org/browse/LB-781), but I can confirm this fixes the follow button appearance and is ready to merge.
Thanks @shivam-kapila !

**Pull request merged**
