### PR TITLE
LB-678: Refactor code in "listenbrainz_spark/utils.py" into multiple files

### PR DESCRIPTION
**Pull request by vibhoooo**
1 -> Ticket ->

LB -678

2 -> Problem ->

There was a file present at this location ->
listenbrainz-server/listenbrainz_spark/utils/__ini__.py
It had some functions related to hdfs that can modify local file system as well as handoop file system.

3 -> Task ->

My task was to move all the files related to hdfs to a new file present in the hdfs folder to avoid confusion.

4 -> Solution/What I did? ->

1 -> Identified functions related to hdfs in __init__.py.
2 -> Made a new file utils.py inside hdfs folder.
3 -> Moved all the functions to this new file.
4 -> Updated imports for the transferred functions.

### CODE REVIEW

**Review by amCap1712 — COMMENTED** [review]
Hi! Thanks for the changes but there are some merge/rebase issues left over. See https://github.com/metabrainz/listenbrainz-server/pull/2286/files#diff-dc930fda680ca3b0389f7eeaba2ee7a868ffa12824edfc8c47d712adaa370fb7R217 etc. Once you clean this up, we can run tests to see if everything is working fine or more changes are needed.

**Comment by vibhoooo** [comment]
I have made changes in __init__.py by removing all the functions moved to utils.py in hdfs folder.

**Comment by vibhoooo** [comment]
I think still tests are failing.

**Comment by vibhoooo** [comment]
For using an imported function I should use -> from listenbrainz_spark import hdfs
or from listenbrainz_spark.hdfs import utils

**Comment by vibhoooo** [comment]
I have made changes in imports.
Please run the tests again to check.

**Comment by amCap1712** [comment]
Sorry for the delay in the review. Thank you for the changes. LGTM.

**Pull request merged**
