### PR TITLE
[LB-103] - Remove magic numbers from ERROR_MESSAGES dictionary.

### PR DESCRIPTION
**Pull request by paramsingh**
Fix for [LB-103](https://tickets.metabrainz.org/projects/LB/issues/LB-103).

One question: errors with code 1 and 19 have the same message ("This error does not exist"),  I've given them names DOES_NOT_EXIST and DOESNT_EXIST, but that doesn't look "right" to me. What would be the best course of action here?

### CODE REVIEW

**Comment by alastair** [comment]
I wonder if error 19 used to be an error message, but last.fm got rid of it: http://www.last.fm/api/errorcodes

I would be fine with calling them `DOES_NOT_EXIST` and `DOES_NOT_EXIST_19`

**Comment by alastair** [comment]
These constants are also used when we raise an `InvalidAPIUsage`, you should use the constant here too.
https://github.com/metabrainz/listenbrainz-server/blob/52c4d795823f72d50bb02748a66b2cfc958beb23/webserver/views/api_compat.py#L97

I wonder if there is a cleaner way of creating this mapping, instead of using both the class to define the constants, and the dictionary to map the numbers to the messages. Perhaps we could have a specific class which represents the number, descriptive value, and error message?

**Comment by alastair** [comment]
What about something like this?
```python
import collections
LfmError = collections.namedtuple('LfmError', ['code', 'message'])

class CompatError(object):
    FOO = LfmError(1, 'cannot do stuff')
    BAR = LfmError(2, 'status ok')

In [6]: error.CompatError.FOO
Out[6]: LfmError(code=1, message='cannot do stuff')

In [7]: error.CompatError.FOO.code
Out[7]: 1

In [8]: error.CompatError.FOO.message
Out[8]: 'cannot do stuff'
```

**Comment by paramsingh** [comment]
@alastair How does this look?

I don't think I've missed any usage of these errors this time.

**Pull request merged**
