### PR TITLE
LB-957: Separate APIService from BrainzPlayer

### PR DESCRIPTION
**Pull request by tandy-1000**
https://tickets.metabrainz.org/browse/LB-957

Initial commit adapts the code from APIService into the `submitListenToListenBrainz` method in BP.

### CODE REVIEW

**Comment by tandy-1000** [comment]
> There are two other instances in this component where we're using the APIService, and then we'll be free to remove any mention of it from this file: `APIService.refreshSpotifyToken` and `APIService.refreshYoutubeToken`, both of which should be passed as [new props to BrainzPlayer](https://github.com/metabrainz/listenbrainz-server/blob/master/listenbrainz/webserver/static/js/src/RecentListens.tsx#L33-L42). Considering my comment below about passing `api_url` as a prop in the same way, it would make sense to do these three changes together (in this PR or in a new one, as you prefer).

No idea if I've done this last part right, wasn't really sure about it.. but should be done now!

**Comment by tandy-1000** [comment]
ping @MonkeyDo :o

**Comment by mayhem** [comment]
Hey @tandy-1000 : Today is a holiday and @MonkeyDo is taking a long weekend. Give him some more time, please!

**Comment by tandy-1000** [comment]
Sorry!! didn't know it was a holiday! take your time monkey :o

**Pull request merged**
