### PR TITLE
LB-148: Add integration tests to api_compat feature

### PR DESCRIPTION
**Pull request by kartikeyaSh**
# Summary
This PR includes some tests for api_compat feature

* This is a…
    * [ ] Bug fix
    * [x] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem
Currently there are no tests for last.fm compatible API. Which makes it hard to debug and figure out
if it's working or not.

* JIRA ticket (_optional_): [LB-148](https://tickets.metabrainz.org/browse/LB-148)

# Solution
Add tests.

### CODE REVIEW

**Comment by kartikeyaSh** [comment]
It depends on PR for LB-308 and LB-309.

**Comment by paramsingh** [comment]
Would it be a lot of work to move relevant tests to their PRs? Perhaps we could merge #353 with just the one test, followed by adding more tests in this PR (or other bugfix PRs)

**Comment by kartikeyaSh** [comment]
Yes, that can be done. Tests in the first 2 commits will pass with current state of API. Should i delete other commits from this PR to make it valid?

**Comment by paramsingh** [comment]
Let's try to get #353 merged first and then you can rebase this.

**Pull request merged**
