### PR TITLE
BrainzPlayer: show draggable youtube player on the page when playing with youtube

### PR DESCRIPTION
**Pull request by MonkeyDo**
In a separate little video screen, and not in the BrainzPlayer cover art thumbnail.
This is required for compliance with Youtube's requirements, and also better user UX.

image

### CODE REVIEW

**Review by amCap1712 — APPROVED** [review]
On mobile screens, a better UX would be if the player does not overlay the listen cards etc and does not always stay on screen (moves as per scroll). But even if we want to do that, it can come later. Thanks!

**Comment by MonkeyDo** [comment]
> On mobile screens, a better UX would be if the player does not overlay the listen cards etc and does not always stay on screen (moves as per scroll). But even if we want to do that, it can come later. Thanks!

So you would have the video under the listencard?

What do you mean by "moves as per scroll"?
I'm keen to makes this better for mobile devices, but the only idea I've had so far is to take advantage of picture-in-picture functionality, which I know don't know enough about :p

**Comment by MonkeyDo** [comment]
OK, I added the react-draggable library as a dependency, and added an icon allowing the user to drag the video anywhere on screen:

image

**Review by amCap1712 — APPROVED** [review]
LGTM, Thanks!

**Comment by Aerozol** [comment]
Wow, I like the draggable option, with the icon. Very clear.
I think this is a good example of an annoying and restrictive requirement turning into a big + thanks to your care and attention Monkey!

**Pull request merged**
