### PR TITLE
LB-511: Raise 400 if the payload doesn't contain any listens

### PR DESCRIPTION
**Pull request by paramsingh**
# Problem

LB-511

We returned a inconsistent "success" string if the payload to `submit-listens` contained no listens.

# Solution

Raise a 400 with an appropriate message and improve documentation.

### CODE REVIEW

**Comment by alastair** [comment]
documentation at https://listenbrainz.readthedocs.io/en/production/dev/json/#submission-json should be updated

**Comment by paramsingh** [comment]
@alastair I added a line to the documentation of the `submit-listens` endpoint.

**Comment by alastair** [comment]
It'd be nice to update the json docs to say that a `playing_now` submission must contain exactly 1 submission. Currently it's still unclear as to if it can contain 0.

**Comment by Zastai** [comment]
@alastair You point to the production docs for a change that I don't think is live yet.
https://listenbrainz.readthedocs.io/en/latest/dev/api/ does show the updated doc already.

**Comment by Zastai** [comment]
Ah never mind, I see what you mean. The JSON docs for the 'import' type don't explicitly say there needs to be at least one. And the others say 'only' which is more ambiguous than 'exactly'.
I'll draft a PR for that part of the docs.

**Pull request merged**
